### ISSUE TITLE
Use REST best practices

### ISSUE THREAD

**Issue by anderruiz** [spring-petclinic/spring-petclinic-angularjs#11]
Hi, first of all thanks for your project, we use it as our showcase for APIs and it is really helpful. Our tool provides security solutions for REST APIs, the more REST principles it follows the easier is to integrate with our tool. We were able to integrate your application but it requires some modifications/configurations and I was wondering if it could be possible to have them fixed, we can even help you on that with a pull request if you want.

The modifications that we are speaking two silly things, REST best practices recommends to use plural nouns for resources, in your project you use:

/owner/*/pet/{petId}
/owner/{ownerId}

And at the same time:

/owners/{ownerId}/pets/{petId}

Is it possible to change them? (the second names would be better but at least they should be the same). Another interesting question is, is the any reason to use weak typing in methods like 

	@GetMapping("/petTypes")
	Object getPetTypes() {
		return clinicService.findPetTypes();
	}

Wouldn't it be better defined as:

	@GetMapping("/petTypes")
	Collection<PetType> getPetTypes() {
		return clinicService.findPetTypes();
	}

Thanks in advance, if you need our assistance just let us know :)

**Comment by arey** [comment]
@anderruiz you're right. By using plural and singular names in URI, we are not consistent. We have to fix it. Plural nouns are better than singular.
Could you please submit a pull request with the changes you propose?
