### ISSUE TITLE
jquery.min.js not found

### ISSUE THREAD

**Issue by phxism** [spring-petclinic/spring-petclinic-angularjs#13]
> spring-petclinic-server\src\main\resources\templates\index.html Line 18,
><script th:src="@{/jquery/dist/jquery.min.js}"></script> will not be found when rendering

**Comment by arey** [comment]
The jquery.min.js path has changed in my last commit: 12da098bba14aecfd0a8e39af4a64f954e40ef61
Did you try to rebuild your project?
On my desktop I've don't have this issue :
> Request URL:http://localhost:8080/jquery/dist/jquery.min.js
> Request Method:GET
> Status Code:200 
> Remote Address:[::1]:8080

**Comment by phxism** [comment]
I git clone two copy of the code in two folder and run the build command in two console, but get different result, two folder bower_components\jquery have two types of jquery the file .bower.json content are not the same :
One 
```
{
  "name": "jquery",
  "main": "dist/jquery.js",
  "license": "MIT",
  "ignore": [
    "package.json"
  ],
  "keywords": [
    "jquery",
    "javascript",
    "browser",
    "library"
  ],
  "homepage": "https://github.com/jquery/jquery-dist",
  "version": "3.2.1",
  "_release": "3.2.1",
  "_resolution": {
    "type": "version",
    "tag": "3.2.1",
    "commit": "77d2a51d0520d2ee44173afdf4e40a9201f5964e"
  },
  "_source": "https://github.com/jquery/jquery-dist.git",
  "_target": "1.9.1 - 3",
  "_originalSource": "jquery"
}
```
the other
```
{
  "name": "jquery",
  "version": "3.2.1",
  "description": "jQuery component",
  "license": "MIT",
  "keywords": [
    "jquery",
    "component"
  ],
  "main": "jquery.js",
  "ignore": [
    "component.json",
    "package.json",
    "composer.json"
  ],
  "homepage": "https://github.com/components/jquery",
  "_release": "3.2.1",
  "_resolution": {
    "type": "version",
    "tag": "3.2.1",
    "commit": "e5534d4ab8e80c159553d507e358ed20a806d3bf"
  },
  "_source": "https://github.com/components/jquery.git",
  "_target": "~3.2.1",
  "_originalSource": "components/jquery"
}
```
I thing that why jquery.min.js is available sometimes and unavailable either.I dont what has causes this problem .I run bower install jquery , it refers to "https://github.com/jquery/jquery-dist.git"

**Comment by arey** [comment]
I've got the same issue by cloning the repo in a new workspace.

**Comment by arey** [comment]
I let you try the patch
