### ISSUE TITLE
Parent project in pom.xml not available

### ISSUE THREAD

**Issue by ghost** [spring-petclinic/spring-petclinic-angularjs#14]
The parent project in pom.xml file is not found, the part

	<parent>
		<groupId>org.springframework.samples</groupId>
		<artifactId>spring-petclinic-angular1</artifactId>
		<version>2.0.0-M2</version>
	</parent>

results in error in IDEA Java 2017.1.3

**Comment by arey** [comment]
Travis build is OK. Did you try to build the project with maven? 
Parent pom is here: https://github.com/spring-petclinic/spring-petclinic-angularjs/blob/master/pom.xml Its sounds OK.
Which modules are in error: client, server or both?
