### ISSUE TITLE
org.hsqldb.jdbcDriver was not found

### ISSUE THREAD

**Issue by hesc** [spring-petclinic/spring-petclinic-angularjs#15]
During startup I get the warning that the hsqldb jdbc driver was not found:

2017-08-15 18:18:19.884  WARN 33322 --- [  restartedMain] com.zaxxer.hikari.util.DriverDataSource  : Registered driver with driverClassName=org.hsqldb.jdbcDriver was not found, trying direct instantiation.

afterwards I got an empty page

**Comment by arey** [comment]
The JDBC Driver for the HSQL Database is declared in the pom.xml:
```
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <scope>runtime</scope>
    </dependency>
```
Maybe a problem with your IDE and the runtime scope?
How do you install the Sprint Petclinic demoi application?

**Comment by hesc** [comment]
I saw this and wondered about the warning.

I built and run the demo in a bash:

- git clone 
- mvnw clean install
- cd spring-petclinic-server
- mvnw spring-boot:run

**Comment by arey** [comment]
Starting from Spring Boot 2.0, database connection strategy has changed. See:
* https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-connect-to-production-database
* http://docs.spring.io/spring-boot/docs/2.0.0.M3/reference/htmlsingle/#boot-features-connect-to-production-database
They know prefer HikariCP to the Tomcat pool.

From my IDE, I have the same warning. But the application is working.
