### ISSUE TITLE
How to run client side

### ISSUE THREAD

**Issue by Shamture** [spring-petclinic/spring-petclinic-angularjs#16]

**Comment by arey** [comment]
Client side is embbeded as a webjar:
```
<dependency>
            <groupId>org.springframework.samples</groupId>
            <artifactId>spring-petclinic-client</artifactId>
        </dependency>
```

**Comment by Shamture** [comment]
Please send me the steps to run this application...

**Comment by arey** [comment]
Do you have read the readme.md?
https://github.com/spring-petclinic/spring-petclinic-angularjs/blob/master/readme.md

**Comment by vikramsvk** [comment]
me too am not able to run the client.

**Comment by arey** [comment]
Here the steps:
```
git clone https://github.com/spring-petclinic/spring-petclinic-angularjs.git
cd spring-petclinic
./mvnw clean install
cd spring-petclinic-server
../mvnw spring-boot:run
```

**Comment by vikramsvk** [comment]
Hi,
There is no folder with "spring-petclinic"!!!!
2nd Step  "cd spring-petclinic" fails.

**Comment by grampi** [comment]
it should be: cd spring-petclinic-angularjs

**Comment by arey** [comment]
Your're right @grampi . I'll update the readme
