### ISSUE TITLE
AngularJS Missing Depedency ?!

### ISSUE THREAD

**Issue by mgabor89** [spring-petclinic/spring-petclinic-angularjs#18]
Hi,

after I've started the server and accessed localhost URL as described in Read.me, 

i.e. `GET http://localhost:8080/angular-ui-router/release/angular-ui-router.min.js`

I get the following in Firefox:

`"http://localhost:8080/angular-ui-router/release/angular-ui-router.min.js".  localhost:8080:22
Error: [$injector:modulerr] Failed to instantiate module petClinicApp due to:
[$injector:modulerr] Failed to instantiate module ui.router due to:
[$injector:nomod] Module 'ui.router' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.6/$injector/nomod?p0=ui.router
minErr/<@http://localhost:8080/angular/angular-79054c75a5ca6ab7e1ecc2247145c34c.js:116:12
module/<@http://localhost:8080/angular/angular-79054c75a5ca6ab7e1ecc2247145c34c.js:2297:17
ensure@http://localhost:8080/angular/angular-79054c75a5ca6ab7e1ecc2247145c34c.js:2218:38
module@http://localhost:8080/angular/angular-79054c75a5ca6ab7e1ecc2247145c34c.js:2295:14
loadModules/<@http://localhost:8080/angular/angular-79054c75a5ca6ab7e1ecc2247145c34c.js:4933:22
forEach@http://localhost:8080/angular/angular-79054c75a5ca6ab7e1ecc2247145c34c.js:410:11
loadModules@http://localhost:8080/angular/a`

**Comment by arey** [comment]
By cloning again the repo, I've got the same error. I will check

**Comment by arey** [comment]
I've fixed the issue. Could you pull my patch and try it again? Thank you

**Comment by mgabor89** [comment]
Now it's working fine. Thanks for fixing it.

Still, when building the client, the following trace appeared:
[ERROR] bower angular-ui-router#^1.0.3         mismatch Version declared in the json (1.0.8) is different than the resolved one (1.0.9)

At the first glance, it doesn't seem to affect the running project though.

**Comment by arey** [comment]
I've updated angular-ui-router to the 1.0.8 version. The error has gone.
