### ISSUE TITLE
Application does not work. Blank Page or css styles not applied. 

### ISSUE THREAD

**Issue by paziljan** [spring-petclinic/spring-petclinic-angularjs#19]
It takes very very long time to start the local host with "waiting local host" message on the browser. It shows either blank page or couple links with no css applied.

**Comment by arey** [comment]
In order to help you, could you please give me more details?
I would like to know if there is a petclinic.css file into the spring-petclinic-angularjs/spring-petclinic-client/target/dist/css directory?
And when you display the homepage, do you see 404 errors? On witch URLs?

**Comment by arey** [comment]
Any feedback
