### ISSUE TITLE
are u open for some cleaning push? 

### ISSUE THREAD

**Issue by eninja** [spring-petclinic/spring-petclinic-angularjs#22]
I did it, but i can't push it. 
![image](https://user-images.githubusercontent.com/1219089/40854410-a025e074-65d1-11e8-8996-2479e1df8d16.png)

**Comment by arey** [comment]
Yes we are. Could you please submit a Pull Request in order to view the change details?

**Comment by eninja** [comment]
i thought i don't have permissions
```
git push origin some-cleaning  
Username for 'https://github.com': eninja  
Password for 'https://eninja@github.com':   
remote: Permission to spring-petclinic/spring-petclinic-angularjs.git denied to eninja.  
fatal: unable to access 'https://github.com/spring-petclinic/spring-petclinic-angularjs.git/': The requested URL returned error: 403
```

**Comment by arey** [comment]
You have to use Pull Request: https://help.github.com/articles/about-pull-requests/

**Comment by eninja** [comment]
Thanks for tip. To be sure - I had to create a fork, right?
